[package]
name = "translate-dir-lib"
version = "0.1.0"
edition = "2024"

[dependencies]
queues = "1.1.0"
serde = {version="1.0.219", features=["std", "derive"]}
serde_json = "1.0.140"
thiserror = "2.0.12"
